### ISSUE TITLE
中文乱码问题

### ISSUE THREAD

**Issue by sentervip** [beatfan/MPC5744P_Bootloader_DownMachine#1]
你好，感谢分享。中文乱码，能解决不，谢谢。

**Comment by zhongranxu** [comment]
同楼上，乱码问题，是怎么解决的？或者可否告知采用何种编译器和编码格式？谢谢

**Comment by zhongranxu** [comment]
//program addr must add 0x800000
void UserFlash_DataParseAddrData(uint8_t *data, uint8_t length)
{
    uint32_t addr;
    uint32_t dataTmp;
    
    addr = data[1]*256*256 + data[2]*256 + data[3] + 0x800000;

该函数写入地址要加上0x800000；是否你在上位机发送的时候减去了0x800000；
是否可以直接用项目的srec文件中的地址来写入，谢谢！

**Comment by beatfan** [comment]
> //program addr must add 0x800000
> void UserFlash_DataParseAddrData(uint8_t *data, uint8_t length)
> {
> uint32_t addr;
> uint32_t dataTmp;
> 
> ```
> addr = data[1]*256*256 + data[2]*256 + data[3] + 0x800000;
> ```
> 
> 该函数写入地址要加上0x800000；是否你在上位机发送的时候减去了0x800000；
> 是否可以直接用项目的srec文件中的地址来写入，谢谢！

是的，上位机为了节约占用can报文字节数量，减去0x800000，将地址缩小为3字节，你后续修改可以自行约定协议，这里的Bootloader仅仅是个范例

**Comment by beatfan** [comment]
> 同楼上，乱码问题，是怎么解决的？或者可否告知采用何种编译器和编码格式？谢谢

前段时间比较慢，没有上Github，乱码问题会在2021年1月10日前修复，为了避免出现编码的问题，会统一采用英文描述

**Comment by beatfan** [comment]
> 你好，感谢分享。中文乱码，能解决不，谢谢。

乱码问题会在2021年1月10日前修复，为了避免出现编码的问题，会统一采用英文描述

**Comment by beatfan** [comment]
乱码问题已修复，此Issue关闭，若有其他问题，可重新打开一个issue
